### ISSUE TITLE
TypeError on ORES ui

### ISSUE THREAD

**Issue by he7d3r** [wiki-ai/ores#120]
1. Open http://ores.wmflabs.org/ui/
2. Select ptwiki
3. Select all models
4. Type the revid 123456
5. Click on "Give me results":

**Expected result**
No error in the console.

**Actual result**
The console shows
> TypeError: $(...).tablesort is not a function

from line [`$('.sortable.table').tablesort();`](https://github.com/wiki-ai/ores/blob/397e8c87861bf99a50aa2557184600269247d824/ores/wsgi/static/js/scorer.js#L88)

**Comment by Ladsgroup** [comment]
It was a bug in using wrong table sort tool: I fixed it in commit 635d51e
