### ISSUE TITLE
Error when setting up development environment

### ISSUE THREAD

**Issue by sabyasachi** [wiki-ai/ores#125]
Here are the steps I followed to setup the development environment:

* On OS X:
```
git clone https://github.com/wiki-ai/ores
cd ores
vagrant up
vagrant ssh
```
Then, once in vagrant virtual machine:
* Configured and activated virtualenv as per https://gist.github.com/halfak/9f4830895496af9e9731
* Then tried to start dev_server
```
git clone https://github.com/wiki-ai/ores
cd ores
utility dev_server
```
* Since the above was complaining about the following missing modules, I installed them:
`docopt`, `yamlconf`, `flask`, `flask-jsonpify`, `stopit`, `celery`, `mwapi`, `revscoring`
* Finally I got stuck at `ImportError: No module named 'revscoring'`, since pip was not installing this, I did `pip install ores`
* Installing ores fails with the error: https://gist.github.com/sabyasachi/4d134c2c2404e0071fe7

**Comment by sabyasachi** [comment]
OK, running `export LC_ALL="en_US.UTF-8"` before `pip install ores` solves this :-)

**Comment by sabyasachi** [comment]
Another error down the line. 
Now when starting dev_server (`./utility dev_server`) getting this: https://gist.github.com/sabyasachi/f92be6069d12a02b3f62

**Comment by halfak** [comment]
I didn't see this issue until now, but we discussed in chat.  Is this now resolved, @sabyasachi?

**Comment by sabyasachi** [comment]
Closing it for now. Will reopen if I see again.
