### ISSUE TITLE
Provide a way to flag scores that seem odd

### ISSUE THREAD

**Issue by Daniel-Mietchen** [wiki-ai/ores#169]
While checking my watchlist on Wikidata, [this edit](https://www.wikidata.org/w/index.php?title=Q24244119&curid=26218085&diff=373494992&oldid=370696363) stuck out in red, with scores of "2% damaging, 84% reverted". The 2% may well be true, but the 84% seem odd to me, given that I could not see anything near 84% reverts for the two items involved, the property or the user.

I think allowing to flag such edits could help finetune the model.

**Comment by Ladsgroup** [comment]
See https://www.wikidata.org/wiki/Wikidata:ORES/Report_mistakes in Wikidata
