### ISSUE TITLE
NaNs appear in ORES output

### ISSUE THREAD

**Issue by halfak** [wiki-ai/ores#177]
For an example that returns NaNs, see https://ores.wmflabs.org/scores/enwiki/wp10 which currently contains 
```
[...]
    "roc": {
      "B": {
        "auc": 0.153
      },
      "C": {
        "auc": NaN
      },
      "FA": {
        "auc": NaN
      },
      "GA": {
        "auc": NaN
      },
      "Start": {
        "auc": NaN
      },
      "Stub": {
        "auc": NaN
      }
    },
[...]
```

This is not up to code with the JSON spec.  See https://tools.ietf.org/html/rfc7159

It happens with python's json.dumps() method.  See https://docs.python.org/3/library/json.html#json.dump  Specifically, there's an `allow_nan` argument that is set to `True` by default.

**Comment by halfak** [comment]
Addressed upstream.

**Comment by Ladsgroup** [comment]
Should we close this?
