### ISSUE TITLE
Indicate progress when running ORES

### ISSUE THREAD

**Issue by ToAruShiroiNeko** [wiki-ai/ores#18]
I think it would be helpful for the code to display a number for say every 100 revisions processed to give an indication of how many have been processed. The number could come after a new line for formatting purposes.

**Comment by he7d3r** [comment]
That seems useful to me.

**Comment by halfak** [comment]
When you're running *what* in ORES?

**Comment by he7d3r** [comment]
@halfak: I assume @ToAruShiroiNeko is referring to the extraction of features from thousands of revisions.

**Comment by halfak** [comment]
Extraction is now part of revscoring.  And FWIW, the --verbose option would give you an indication of progress.
