### ISSUE TITLE
How does one submit multiple IDs?

### ISSUE THREAD

**Issue by Ironholds** [wiki-ai/ores#182]
I've been tinkering with the 2.0 API and the docs (https://ores.wmflabs.org/v2/#!/scoring/get_v2_scores_context_model) suggest that multiple IDs at a time is a-ok, but I can't work out the format I'm meant to be submitting them in - a JSON blob, comma-separated..?

**Comment by Ladsgroup** [comment]
Hey Oliver, If you mean to the service, Something like https://ores.wikimedia.org/v2/scores/enwiki/?models=damaging&revids=724030089 would work (I guess it's not very RESTful but okay-ish)

**Comment by Ladsgroup** [comment]
(I forgot: https://ores.wikimedia.org/v2/scores/enwiki/?models=damaging|goodfaith&revids=724030089|122233 )

**Comment by Ironholds** [comment]
Ahh, pipe-separated; thanks! I can work with that.
