### ISSUE TITLE
Do not redirect from https to http

### ISSUE THREAD

**Issue by he7d3r** [wiki-ai/ores#25]
Currently if I access
https://ores-test.wmflabs.org/scores/ptwiki?models=reverted&revids=42150243
I get redirected to
http://ores-test.wmflabs.org/scores/ptwiki/?models=reverted&revids=42150243

In particular, when loading such an URL in JavaScript from an https:// page, the target will be blocked due to
https://developer.mozilla.org/docs/Security/MixedContent

In my script, I had to add the "/" to the end of the URL as a workaround:
https://github.com/he7d3r/mw-gadget-RCScoreFilter/commit/50ad171e1f8892bff603f37d1b267d0c88ce8308

**Comment by halfak** [comment]
I think this is flask doing a redirect that behaves badly with the labs proxy.

**Comment by halfak** [comment]
Finally resolved.  We had to go https only.
