### ISSUE TITLE
Asking for the scores of many revisions takes too long

### ISSUE THREAD

**Issue by he7d3r** [wiki-ai/ores#26]
I wanted the scores of [50 revisions](https://ores-test.wmflabs.org/scores/ptwiki/?callback=jQuery1112009417782616493897_1429733035682&models=reverted&revids=42150603|42150525|42150508|42150434|42150340|42150243|42150062|42150011|42150010|42149709|42149483|42149358|42148583|42148004|42147329|42146093|42146084|42145888|42145841|42145578|42144883|42144875|42144833|42144787|42144377|42073538|42073530|42058566|42058490|42057547|42056996|42055739|42055578|42055468|42055245|42055002|42054957|42053522|42053278|42052567|42052070|42051271|42049939|42049732|42049349|42049128|42048975|42048818|42037627|42008898&_=1429733035685), but ores took 74 seconds to respond.

See also [meta:Research talk:Revision scoring as a service#Notes on ORES performance.](https://meta.wikimedia.org/wiki/Research_talk:Revision_scoring_as_a_service#Notes_on_ORES_performance.)

**Comment by halfak** [comment]
Relatedly see: https://github.com/halfak/Revision-Scoring/pull/97

It gets us about a 50% speedup for batch requests of 50 revisions or more

**Comment by halfak** [comment]
We've made substantial improvements to performance.
