### ISSUE TITLE
Make it possible to specify a base path for the model files

### ISSUE THREAD

**Issue by yuvipanda** [wiki-ai/ores#40]
Makes it easy to locate them in a flexible way

**Comment by halfak** [comment]
Model file paths are relative to the installation directory, but can be specified absolutely.   It seems that, if we're going to have a base path, we'll want to specify a data directory for NLTK and all that jazz too.  Does that make sense, or would you rather just use absolute paths?

**Comment by halfak** [comment]
wontfix

**Comment by yuvipanda** [comment]
Yeah, the 'can be specified absolutely' makes this all ok.
