### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by yuvipanda** [wiki-ai/ores#45]
We should enable CORS so tools that want to use CORS can use it instead of having to rely on JSONP.

**Comment by kenrick95** [comment]
:+1: on this

**Comment by halfak** [comment]
@kenrick95 in the meantime, you can take advantage of jsonp 

For example http://ores.wmflabs.org/scores/enwiki/reverted/642215410/?callback=mycallback

**Comment by kenrick95** [comment]
Yeah currently I'm using JSONP though I'd like to see CORS support in the future 😊 

Kenrick

-----Original Message-----

**Comment by Krinkle** [comment]
In RTRC there's a demand for adding annotations from ORES (https://github.com/Krinkle/mw-gadget-rtrc/pull/43). Using CORS would make these requests cacheable (both server-side and client-side).

I've recently implemented CORS and HTTP caching in two other APIs as well, which may help:
* https://github.com/countervandalism/cvn-api/commit/27c7ea999b
* https://github.com/Krinkle/intuition/commit/f087cc1d01327

**Comment by ricordisamoa** [comment]
:+1:

**Comment by yuvipanda** [comment]
Since ORES is fully readonly and only GET I can maybe just enable CORS on the nginx side?

**Comment by halfak** [comment]
This is done.

**Comment by he7d3r** [comment]
I updated a few scripts to use this:
* https://github.com/he7d3r/mw-gadget-ScoredRevisions/commit/b7478c213b05b9b09816bf1d723dea7e6e951968
* https://github.com/he7d3r/mw-gadget-ScoredCategories/commit/c28e417feaa4a47ca058660cf92c76f748df27a5
* https://github.com/he7d3r/mw-gadget-TopRevisionsByScore/commit/8e42ba8e2386c1ed82741e2b2038053670c2e980

However, when I run
```javascript
$.ajax( {
    url: 'https://ores.wmflabs.org/scores/' + mw.config.get( 'wgDBname' ),
    dataType: 'json'
} ).done( function ( data ) {
    alert( 'Data:\n\n' + JSON.stringify( data ) );
} );
```
I get this on wiktionary and mediawikiwiki:
>Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ores.wmflabs.org/scores/enwiktionary/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://ores.wmflabs.org/scores/mediawikiwiki/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

(notice also the redirect to http!)
