### ISSUE TITLE
ORES gives 500 Internal Server Error on revert score query for imported revisions

### ISSUE THREAD

**Issue by gpaumier** [wiki-ai/ores#60]
ORES chokes on this URL: http://ores.wmflabs.org/scores/enwiki/?revids=408030634&models=reverted and returns a 500 Internal Server Error.

My hypothesis is that this is because that very early revision was lost, and later [restored from the nostalgia Wikipedia](https://en.wikipedia.org/wiki/User:Graham87/Import). ORES gives the same error when requesting the revert score of the other imported revision: http://ores.wmflabs.org/scores/enwiki/?revids=408030635&models=reverted

Instead of a server error, it should probably return the same kind of "nice" error as when a revision was deleted.

I discovered this while building [archaeo](https://github.com/gpaumier/archaeo). As part of the [associated Wikimania talk](https://wikimania2015.wikimedia.org/wiki/Submissions/Let%27s_talk_about_bees:_What_a_single_Wikipedia_article_can_tell_us_about_Wikipedians), I'm fetching scores for all revisions of the [Bee article](https://en.wikipedia.org/wiki/Bee) on the English Wikipedia.

If it helps, [Quarry 3990](http://quarry.wmflabs.org/query/3990) provides the list of all revisions for "Bee". The imported revisions are chronologically the first ones (they have the earliest `rev_timestamp`s) but they have very high `rev_id`s.

**Comment by gpaumier** [comment]
Note: I don't know if this happens for *all* imported revisions, but it does happen for imported revisions of other pages as well: ORES returns the same [server error](http://ores.wmflabs.org/scores/enwiki/?revids=332479164&models=reverted) for [this other imported revision](https://en.wikipedia.org/w/index.php?title=River&diff=332479164&oldid=277554).

**Comment by halfak** [comment]
Thanks for reporting this and going some digging @gpaumier.  It looks like this is the error that is being thrown.  

```
RuntimeError('Failed to process <log((user.age + 1))>: math domain error',)
Traceback (most recent call last):
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/ores-0.2.0-py3.4.egg/ores/score_processors/celery.py", line 33, in _process
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/ores-0.2.0-py3.4.egg/ores/scoring_contexts/scoring_context.py", line 46, in score
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/revscoring-0.4.0-py3.4.egg/revscoring/dependencies/functions.py", line 240, in _solve_many
  File "/home/halfak/env/3.4/lib/python3.4/site-packages/revscoring-0.4.0-py3.4.egg/revscoring/dependencies/functions.py", line 231, in _solve
RuntimeError: Failed to process <log((user.age + 1))>: math domain error
```
It looks like the import results in a revision with a timestamp that is impossible given a user's registration date.  We'll want to bound user.age to zero to fix the issue.  So it looks like this is a 'revscoring' problem.  I'll file a stub bug there referencing this can get a PR up.

**Comment by halfak** [comment]
See https://github.com/wiki-ai/revscoring/issues/122 and https://github.com/wiki-ai/revscoring/pull/123

**Comment by halfak** [comment]
I've also confirmed that changes made in https://github.com/wiki-ai/ores/pull/57 will also solve the 500 Internal Server Error problem so that errors like this in the future will return a useful response.

**Comment by gpaumier** [comment]
Great! Thank you. I assumed that the issue was with revscoring, but I wasn't sure, so I reported it here. Thanks for fixing this so quickly!
