### ISSUE TITLE
Provide machine-readable information on models

### ISSUE THREAD

**Issue by sitic** [wiki-ai/ores#66]
Basically https://meta.wikimedia.org/wiki/ORES/reverted and https://meta.wikimedia.org/wiki/ORES/wp10 in json from. (The list of wikis available for a model and the corresponding accuracy).

**Comment by halfak** [comment]
+1  See also https://github.com/wiki-ai/revscoring/issues/180

Making that change would ensure that this type of information is stored with a model.

**Comment by halfak** [comment]
Fixed in https://github.com/wiki-ai/ores/pull/97 and deployed.
