### ISSUE TITLE
Ores should return predictions for available models even if requested together with missing models

### ISSUE THREAD

**Issue by he7d3r** [wiki-ai/ores#76]
Currently, there is a "revert" model for a ptwiki:
http://ores.wmflabs.org/scores/ptwiki/?models=reverted&revids=41338880|41339445
```javascript
{
  "41338880": {
    "reverted": {
      "prediction": true,
      "probability": {
        "false": 0.2614995893827041,
        "true": 0.7385004106172957
      }
    }
  },
  "41339445": {
    "reverted": {
      "prediction": false,
      "probability": {
        "false": 0.8541050428468395,
        "true": 0.14589495715316042
      }
    }
  }
}
```
but the modules "goodfaith" and "damaging" are not available yet. This should not make the following request to fail completely:
http://ores.wmflabs.org/scores/ptwiki/?models=reverted|damaging|goodfaith&revids=41338880|41339445
```javascript
{
  "error": {
    "code": "bad request",
    "message": "Models '['goodfaith', 'damaging']' not available for ptwiki."
  }
}
```

I expected a response which would contain the predictions for the available modules, and error messages for the others. E.g.:
```javascript
{
  "error": {
    "code": "bad request",
    "message": "Models '['goodfaith', 'damaging']' not available for ptwiki."
  }
  "41338880": {
    "reverted": {
      "prediction": ...
    }
  },
  "41339445": {
    "reverted": {
      "prediction": ...
    }
  }
}
```
or even a more verbose output like
```javascript
{
  "41338880": {
    "reverted": {
      "prediction": ...
    },
    "goodfaith": {
      "error": ...
    },
    "damaging": {
      "error": ...
    }
  },
  "41339445": {
    "reverted": {
      "prediction": ...
    },
    "goodfaith": {
      "error": ...
    },
    "damaging": {
      "error": ...
    }
  }
}
```

**Comment by halfak** [comment]
I'm not sure I agree.  Imagine how many bits we would waste if a service was requesting a set of models and handling the error silently.  I think it's best to error when there is anything wrong with the request and require our users to get it right.

**Comment by halfak** [comment]
Closing wontfix
